#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanAgustin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "SanAgustin")]
    public partial class DataClasses1DataContext : System.Data.Linq.DataContext
    {
        partial void OnCreated()
        {
            this.CommandTimeout = 3600;
        }

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        public DataClasses1DataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SanAgustinConectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<Bautizos> bautizos
        {
            get { return this.GetTable<Bautizos>(); }
        }

        public System.Data.Linq.Table<Bodas> Bodas
        {
            get { return this.GetTable<Bodas>(); }
        }

        public System.Data.Linq.Table<Cargos> Cargos
        {
            get { return this.GetTable<Cargos>(); }
        }

        public System.Data.Linq.Table<Comunidades> Comunidades
        {
            get { return this.GetTable<Comunidades>(); }
        }

        public System.Data.Linq.Table<Confirmacion> Confirmacion
        {
            get { return this.GetTable<Confirmacion>(); }
        }

        public System.Data.Linq.Table<InfAdicional> InfAdicional
        {
            get { return this.GetTable<InfAdicional>(); }
        }

        public System.Data.Linq.Table<Personal> PersonalSA
        {
            get { return this.GetTable<Personal>(); }
        }

        public System.Data.Linq.Table<PrimeraComunion> PrimeraComunion
        {
            get { return this.GetTable<PrimeraComunion>(); }
        }

        public System.Data.Linq.Table<Sacramentos> Sacramentos
        {
            get { return this.GetTable<Sacramentos>(); }
        }
    }
}
#pragma warning restore 1591
